### ISSUE TITLE
Getters and Setters

### ISSUE THREAD

**Issue by bclinthall** [JaysGitLab/cs5666-spr17-javatrix-ccubed#66]
- [x] #18 get(int i, int j)
- [x] #19 getArray()
- [ ] #20 getArrayCopy() - write `double[][] copyArray(double[][] array)` helper method
- [x] #31 getColumnDimension()
- [x] #37 getRowDimsion()
- [x] #51 random(int m, int n)
- [x] #53 set(int i, int j, double s)
- [x] #54 void setMatrix(int[] r, int[] c, Matrix X)
